import {StyleSheet, Dimensions} from 'react-native';
import {COLORS, FONTS} from '../../constants';
const {height, width} = Dimensions.get('window');
export default StyleSheet.create({
  container: {
    backgroundColor: COLORS.white,
    flex: 1,
  },
  innercontainer: {
    width: width * 0.94,
    alignSelf: 'center',
    backgroundColor: COLORS.white,
  },
  blog: {
    color: COLORS.gray60,
    fontSize: 14,
    ...FONTS.sixHundred,
    margin: width * 0.01,
  },
  viewofferbox: {
    flexDirection: 'row',
    marginVertical: height * 0.02,
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: COLORS.gray10,
    borderRadius: 6,
    alignItems: 'center',
    width: width * 0.93,
    paddingVertical: height * 0.012,
  },
  viewoffertext: {
    fontSize: 13,
    color: COLORS.black,
    fontFamily: FONTS.medium,
    marginBottom: -3,
    width: width * 0.73,
  },
  percent: {
    height: height * 0.032,
    width: width * 0.08,
    resizeMode: 'contain',
    marginHorizontal: width * 0.02,
  },
  arrow: {
    height: height * 0.03,
    width: width * 0.045,
    resizeMode: 'contain',
    tintColor: COLORS.black,
  },
  price_bottom: {
    borderColor: COLORS.gray10,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    paddingHorizontal: width * 0.05,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderWidth: 1,
    marginBottom: 2,
    paddingVertical: height * 0.006,
  },
  bottom_text1: {
    ...FONTS.sixHundred,
    color: COLORS.black,
    fontSize: 16,
    marginBottom: height * -0.01,
    textAlign: 'center',
  },
  bottom_text2: {
    color: COLORS.green,
    fontSize: 12,
    ...FONTS.fiveHundred,
  },
  addmorebox: {
    borderWidth: 1,
    borderColor: COLORS.red,
    alignSelf: 'center',
    marginBottom: height * 0.02,
    flexDirection: 'row',
    alignItems: 'center',
    width: width * 0.93,
    justifyContent: 'center',
    height: height * 0.056,
    borderRadius: 6,
    backgroundColor: COLORS.white,
  },
  plus: {
    height: height * 0.03,
    width: width * 0.043,
    resizeMode: 'contain',
    marginHorizontal: width * 0.02,
  },
  addmore: {
    fontSize: 13,
    color: COLORS.red,
    fontFamily: FONTS.semiBold,
    marginBottom: -3,
  },
  modalbox: {
    alignItems: 'center',
    width: width * 0.8,
    backgroundColor: 'white',
    borderRadius: 12,
    paddingVertical: height * 0.02,
    alignSelf: 'center',
  },
  modalhead: {
    fontSize: 14,
    color: COLORS.red,
    marginVertical: height * 0.015,
    fontFamily: FONTS.semiBold,
    alignSelf: 'center',
  },
  modalbtnrow: {
    flexDirection: 'row',
    marginVertical: height * 0.03,
  },
});
