import {StyleSheet, Dimensions} from 'react-native';
import {COLORS, FONTS} from '../../constants';
const {width, height} = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    backgroundColor: COLORS.white,
    flex: 1,
  },
  flatlistBox: {
    width: width * 0.92,
    alignSelf: 'center',
  },
  rowbtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    marginBottom: height * 0.015,
    borderTopWidth: 1,
    borderColor: COLORS.gray10,
    paddingTop: height * 0.015,
    backgroundColor: COLORS.white,
  },
  rowlist: {flexDirection: 'row'},
  switchbox: {
    borderWidth: 1,
    borderColor: COLORS.gray10,
    height: height * 0.055,
    marginVertical: width * 0.025,
    borderRadius: 10,
    width: width * 0.37,
    justifyContent: 'center',
    backgroundColor: COLORS.white,
    marginLeft: width * 0.022,
    marginRight: width * 0.02,
  },
  switchtext: {
    textAlign: 'center',
    ...FONTS.fiveHundred,
    color: COLORS.black,
    fontSize: 12,
  },
  dot: {
    width: width * 0.02,
    backgroundColor: COLORS.gray70,
    height: width * 0.02,
    borderRadius: 20,
    marginRight: width * 0.025,
    marginTop: width * 0.015,
  },
  dotText: {
    color: COLORS.black,
    fontSize: 13,
    ...FONTS.fiveHundred,
    alignSelf: 'center',
    width: width * 0.9,
  },
  dotrow: {
    flexDirection: 'row',
    marginLeft: width * 0.04,
    marginTop: width * 0.02,
  },

  starbox: {
    flexDirection: 'row',
    alignSelf: 'center',
    width: width * 0.87,
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: height * 0.005,
  },
  usercount: {
    fontSize: 11.5,
    fontFamily: FONTS.medium,
    color: COLORS.black,
    width: width * 0.25,
  },
  starstyle: {
    width: width * 0.26,
    alignItems: 'flex-start',
  },
  starmainbox: {
    borderWidth: 1,
    width: width * 0.93,
    alignSelf: 'center',
    paddingVertical: height * 0.01,
    borderColor: COLORS.gray10,
    borderRadius: 8,
    marginBottom: height * 0.02,
  },
  heading: {
    fontSize: 15,
    fontFamily: FONTS.semiBold,
    color: COLORS.black,
    marginLeft: width * 0.04,
    marginVertical: height * 0.01,
  },
  viewofferbox: {
    flexDirection: 'row',
    marginVertical: height * 0.02,
    alignSelf: 'center',
    borderWidth: 1,
    borderColor: COLORS.gray10,
    borderRadius: 6,
    alignItems: 'center',
    width: width * 0.93,
    paddingVertical: height * 0.012,
  },
  viewoffertext: {
    fontSize: 13,
    color: COLORS.black,
    fontFamily: FONTS.medium,
    marginBottom: -3,
    width: width * 0.73,
  },
  percent: {
    height: height * 0.032,
    width: width * 0.08,
    resizeMode: 'contain',
    marginHorizontal: width * 0.02,
  },
  arrow: {
    height: height * 0.03,
    width: width * 0.045,
    resizeMode: 'contain',
    tintColor: COLORS.black,
  },
  iicon: {
    height: height * 0.035,
    width: width * 0.054,
    resizeMode: 'contain',
    tintColor: COLORS.red,
    marginLeft: width * 0.08,
  },
  inputBox: {
    width: width * 0.92,
    borderWidth: 1,
    borderColor: COLORS.gray20,
    borderRadius: 8,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
  },
  available: {
    ...FONTS.sixHundred,
    fontSize: 13,
    marginBottom: -3,
    color: COLORS.green,
  },
  placeholdera: {
    ...FONTS.fiveHundred,
    fontSize: 13,
    marginBottom: -3,
    color: COLORS.black,
    paddingLeft: width * 0.03,
    width: width * 0.72,
  },

  ratings: {
    color: COLORS.black,
    fontSize: 11,
    width: width * 0.2,
    ...FONTS.fiveHundred,
  },
  ratebox: {
    width: width * 0.12,
    backgroundColor: COLORS.green,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: width * 0.003,
    justifyContent: 'center',
    borderRadius: 3,
    marginRight: width * 0.02,
  },
  rate: {
    color: COLORS.white,
    fontSize: 12,
    ...FONTS.fiveHundred,
    marginBottom: -3,
    marginRight: width * 0.015,
  },
  star: {
    width: width * 0.028,
    height: height * 0.014,
    resizeMode: 'stretch',
    tintColor: COLORS.white,
  },

  subtitle: {
    color: COLORS.black,
    fontSize: 12.5,
    ...FONTS.fiveHundred,
    width: width * 0.94,
    alignSelf: 'center',
    marginTop: height * 0.015,
    marginBottom: height * 0.005,
  },
  mrp: {
    color: COLORS.gray60,
    fontSize: 13,
    ...FONTS.fiveHundred,
  },
  mrpprice: {
    color: COLORS.gray60,
    fontSize: 13,
    ...FONTS.fiveHundred,
    width: width * 0.15,
    textDecorationLine: 'line-through',
  },
  off: {
    color: COLORS.green,
    fontSize: 12,
    ...FONTS.sixHundred,
  },
  price: {
    color: COLORS.black,
    fontSize: 14,
    ...FONTS.sixHundred,
    width: width * 0.18,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: height * 0.004,
  },
  btnstyle: {
    marginBottom: height * 0.03,
    marginLeft: width * 0.04,
  },
  error: {
    color: COLORS.primary,
    fontSize: 12,
    ...FONTS.fourHundred,
    marginLeft: width * 0.04,
  },
});
