export const USER_STATE = 'USER_STATE';
export const LOADING = 'LOADING';
export const AUTH_TOKEN = 'AUTH_TOKEN';
export const GET_USER = 'GET_USER';
export const HOME_DATA = 'HOME_DATA';
export const GET_PARENT_CATEGORIES = 'GET_PARENT_CATEGORIES';
export const GET_SUB_CATEGORIES = 'GET_SUB_CATEGORIES';
export const GET_BYPRODUCT_ID = 'GET_BYPRODUCT_ID'; //category page
export const CREATE_CARDS = 'CREATE_CARDS';
export const GET_COUPON = 'GET_COUPON';
export const GET_ALL_CARTS = 'GET_ALL_CARTS';
export const GET_ADDRESS_BYUSERID = 'GET_ADDRESS_BYUSERID';
export const GET_ADDRESS_BYID = 'GET_ADDRESS_BYID';
export const GET_PINCODE = 'GET_PINCODE';